version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-books:test
    container_name: go_books_app
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      - JWT_SECRET=
    ports:
      - "8080:8080"
    depends_on:
      - db
